# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://{{host}}/api/rest/wechat_connect/js-sdk-config?_format=json
Content-Type: application/json

{
  "app_id": "wx1f7851dc1b2f3e03",
  "url":"http://home.aiqilv.com",
  "apis": ["onMenuShareTimeline", "onMenuShareAppMessage"]
}

###
# 获取openid，创建账号
# 返回 Oauth2 code，用此 code 可获取 Oauth2 access_token
POST http://{{host}}/api/rest/wechat_connect/connect?_format=json
Content-Type: application/json

{
  "client_id": "Oauth2登录client_id",
  "app_id": "小程序app_id",
  "code": "小程序wx.login拿到的code"
}

### 微信小程序上传文件
POST {{host}}/wechat-connect/upload-file?_format=json
Content-Type: multipart/form-data
Authorization: Basic {{username}} {{password}}

###
# 微信授权登录：原生 APP
POST {{host}}/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=wechat_native_app_code&client_id={{client_id}}&client_secret={{client_secret}}&code={{wechat_native_app_code}}&scope=

###
# 微信授权登录：微信小程序
POST {{host}}/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=wechat_mini_program_code&client_id={{client_id}}&client_secret={{client_secret}}&code={{wechat_native_app_code}}&scope=

###
# 微信授权登录：Web 应用(Website/公众号h5)
